FROM golang:1.12

WORKDIR /app

COPY . .

ARG MAILROOM_PARSE_SERVER_APP_ID
ENV MAILROOM_PARSE_SERVER_APP_ID=$MAILROOM_PARSE_SERVER_APP_ID

ARG MAILROOM_PARSE_SERVER_MASTER_KEY
ENV MAILROOM_PARSE_SERVER_MASTER_KEY=$MAILROOM_PARSE_SERVER_MASTER_KEY

ARG MAILROOM_PARSE_SERVER_URL
ENV MAILROOM_PARSE_SERVER_URL=$MAILROOM_PARSE_SERVER_URL

ARG MAILROOM_FDL_DEFAULT_URL
ENV MAILROOM_FDL_DEFAULT_URL=$MAILROOM_FDL_DEFAULT_URL

ARG MAILROOM_FDL_KEY
ENV MAILROOM_FDL_KEY=$MAILROOM_FDL_KEY

RUN go build ./cmd/... && chmod +x mailroom

EXPOSE 80
ENTRYPOINT ["./mailroom"]