package models

import (
	"fmt"
	"os/exec"
	"testing"

	"github.com/jmoiron/sqlx"
)

// Reset resets our database to our state as specified in temba.sql
//
// temba.sql can be regenerated by running:
//   % python manage.py test_db generate --seed 1337
//   % pg_dump -F c temba > temba.dump
func Reset(t *testing.T) *sqlx.DB {
	// restore our db using pg_restore
	cmd := exec.Command("pg_restore", "-d", "temba", "-c", "temba.dump")
	err := cmd.Run()
	if err != nil {
		panic(fmt.Sprintf("error restoring database: %s", err))
	}

	db := sqlx.MustOpen("postgres", "postgres://temba@localhost/temba?sslmode=disable")
	return db
}
